/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN = 5;
  /** RegularExpression Id. */
  int CLOSE = 6;
  /** RegularExpression Id. */
  int DEFINE = 7;
  /** RegularExpression Id. */
  int DOMAIN = 8;
  /** RegularExpression Id. */
  int DOMAIN_LABEL = 9;
  /** RegularExpression Id. */
  int REQUIREMENTS = 10;
  /** RegularExpression Id. */
  int REQUIREMENT_LABELS = 11;
  /** RegularExpression Id. */
  int TYPES = 12;
  /** RegularExpression Id. */
  int PREDICATES = 13;
  /** RegularExpression Id. */
  int PROBLEM = 14;
  /** RegularExpression Id. */
  int TYPE_IDENT = 15;
  /** RegularExpression Id. */
  int VAR = 16;
  /** RegularExpression Id. */
  int ACTION = 17;
  /** RegularExpression Id. */
  int PARAMETERS = 18;
  /** RegularExpression Id. */
  int PRECONDITION = 19;
  /** RegularExpression Id. */
  int CONSTRAINTS = 20;
  /** RegularExpression Id. */
  int PREFERENCE = 21;
  /** RegularExpression Id. */
  int EFFECT = 22;
  /** RegularExpression Id. */
  int OBJECTS = 23;
  /** RegularExpression Id. */
  int GOAL = 24;
  /** RegularExpression Id. */
  int INIT = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int NOT = 27;
  /** RegularExpression Id. */
  int NUMBER = 28;
  /** RegularExpression Id. */
  int NAME = 29;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"define\"",
    "\"domain\"",
    "\":domain\"",
    "\":requirements\"",
    "\":typing :constraints :preferences\"",
    "\":types\"",
    "\":predicates\"",
    "\"problem\"",
    "\"-\"",
    "<VAR>",
    "\":action\"",
    "\":parameters\"",
    "\":precondition\"",
    "\":constraints\"",
    "\"preference\"",
    "\":effect\"",
    "\":objects\"",
    "\":goal\"",
    "\":init\"",
    "\"and\"",
    "\"not\"",
    "<NUMBER>",
    "<NAME>",
    "<SINGLE_LINE_COMMENT>",
  };

}
